- block:
    - name: check if {{ project }} project exists
      uri:
        url: http://gerrit:8080/projects/{{ project }}
  rescue:
    - name: create temp dir for {{ project }} creation
      shell: mktemp -d
      register: project_tmp
    - name: create {{ project }} project
      uri:
        url: http://gerrit:8080/a/projects/{{ project }}
        method: PUT
        user: admin
        password: secret
        status_code: 201
    - name: create initial commit
      shell:
        executable: /bin/bash
        chdir: "{{ project_tmp.stdout }}"
        cmd: |
          git init .
          git config user.name "Admin"
          git config user.email "admin@example.com"
          cat >.gitreview <<EOF
          [gerrit]
          host=localhost
          port=29418
          project={{ project }}
          EOF
          git add .gitreview
          git commit -m "Initial commit"
          git remote add gerrit http://admin:secret@gerrit:8080/{{ project }}
          git push -f --set-upstream gerrit +HEAD:master
