---
- name: Check if tools/tests-setup.sh exists.
  stat:
    path: "/home/zuul/workspace/src/{{ zuul.project }}/tools/setup.sh"
  register: p

- name: Run tools/test-setup.sh.
  shell: tools/test-setup.sh
  args:
    chdir: "/home/zuul/workspace/src/{{ zuul.project }}"
  when: p.stat.executable
