---
upgrade:
  - |
    Schedulers will no longer trigger a smart-reconfig after startup and with
    that also not pick up modifications to the local tenant config with a
    restart of a scheduler. This means that changes to the tenant config always
    require an explicit (smart) reconfiguration.
