---
upgrade:
  - |
    Zuul-web now requires access to the Zookeeper keystore.  Ensure that
    the :attr:`keystore.password` option is included in ``zuul.conf``
    on at least the scheduler, executor, and web servers (it may be included
    on all components if desired).
