- name: "Setup repository {{ project_name }}"
  shell:
    chdir: "{{ workspace }}/"
    executable: /bin/bash
    cmd: |
      git clone --config http.https://localhost:8081/.sslVerify=false https://user:{{ gitlab_user_token.json['token'] }}@localhost:8081/tutorial/{{ project_name }}
      cd {{ project_name }}
      git config user.email 'user@example.com'
      git config user.name 'Example User'
