- name: Copy logs from old side of test run
  delegate_to: localhost
  shell: |
    mkdir {{ zuul.executor.work_root }}/logs/old
    mv {{ zuul.executor.work_root }}/logs/* {{ zuul.executor.work_root }}/logs/old
