- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - log-inventory

- hosts: all
  roles:
    - add-build-sshkey
    - role: prepare-workspace
      zuul_workspace_root: "{{ zuul.build }}"
