- hosts: all
  tasks:

    - name: Install pbrx software
      command: python3 -m pip install src/git.openstack.org/openstack/pbrx
      become: yes

    - name: Install pre-reqs
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      become: yes

    - name: Add docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      become: yes

    - name: Add docker apt repo
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      become: yes

    - name: Install docker
      package:
        name: docker-ce
        state: present

    - name: Add zuul user to docker group
      become: yes
      user:
        name: zuul
        groups:
          - docker
        append: yes
