---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-use-zuul-jobs-test
    local: true
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ssh_agent:
      stdout: ''
  tasks:
    - include_tasks: ../setup-tutorial/setup.yaml
    - include_tasks: ../gate-first-patch/main.yaml
    - include_tasks: main.yaml
