- name: Install python modules selenium webdriver-manager
  command: python3 -m pip install selenium
  become: true

- name: Run selenium container
  shell:
    executable: /bin/sh
    cmd: |
      docker run -d --network host -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:4.1.3

- name: Wait for selenium to br ready
  uri:
    url: "http://localhost:4444/wd/hub/status"
    method: GET
    status_code: 200
  register: selenium
  until: selenium.status == 200 and selenium.json.value.ready == true
  delay: 1
  retries: 30

- name: Run Zuul Web Test
  zuul-web-test:
