- name: Install python module selenium
  command: python3 -m pip install selenium
  become: true
  when: not local|default(true)

- name: Run selenium container
  docker_container:
    name: zuul-tutorial_selenium
    image: selenium/standalone-firefox:4.1.3
    state: started
    restart: yes
    network_mode: host
    mounts:
      - source: /dev/shm
        target: /dev/shm
        type: bind

- name: Wait for selenium to be ready
  uri:
    url: "http://localhost:4444/wd/hub/status"
    method: GET
    status_code: 200
  register: selenium
  until: selenium.status == 200 and selenium.json.value.ready == true
  delay: 1
  retries: 30

- name: Run Zuul Web Test
  zuul-web-test:
