- hosts: controller
  tasks:

    - name: Run ansible
      command: ansible-playbook -vvv src/git.openstack.org/openstack-infra/zuul/playbooks/zuul-stream/fixtures/test-stream.yaml
      environment:
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ARA_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"

    - name: Run ansible playbook that should fail
      command: ansible-playbook -vvv src/git.openstack.org/openstack-infra/zuul/playbooks/zuul-stream/fixtures/test-stream-failure.yaml
      register: failed_results
      failed_when: "failed_results.rc != 2"
      environment:
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ARA_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"

    - name: Generate ARA html
      command: ara generate html ara-output

    - name: Compress ARA html
      command: gzip --recursive --best ara-output
