- hosts: controller
  tasks:

    - name: Install zuul
      command: python3 -m pip install src/git.openstack.org/openstack-infra/zuul
      become: yes

    - name: Install ARA
      command: python3 -m pip install src/git.openstack.org/openstack/ara
      become: yes

    - name: Generate logging config
      command: python3 src/git.openstack.org/openstack-infra/zuul/zuul/lib/logconfig.py

    - name: Run ansible
      command: ansible-playbook -vvv src/git.openstack.org/openstack-infra/zuul/playbooks/zuul-stream/fixtures/test-stream.yaml
      environment:
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ARA_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json

    - name: Generate ARA html
      command: ara generate html ara-output

    - name: Compress ARA html
      command: gzip --recursive --best ara-output
