- hosts: controller
  tasks:
    - name: Set python path fact
      set_fact:
        python_path: "/usr/local/lib/python3.6/dist-packages"

    - name: Retrieve path to ARA callback plugin
      command: /usr/lib/zuul/ansible/{{ zuul_ansible_version}}/bin/python3 -m ara.setup.callback_plugins
      register: ara_callback_plugins

    - name: Run ansible that should succeed
      command: >
        /usr/lib/zuul/ansible/{{ zuul_ansible_version }}/bin/ansible-playbook
        src/opendev.org/zuul/zuul/playbooks/zuul-stream/fixtures/test-stream.yaml
      environment:
        ANSIBLE_CALLBACK_PLUGINS: "{{ ara_callback_plugins.stdout }}:{{ python_path }}/zuul/ansible/base/callback"
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ZUUL_JOBDIR: "{{ ansible_user_dir}}"
        PYTHONPATH: "{{ python_path }}"

    - name: Run ansible playbook that should fail
      command: >
        /usr/lib/zuul/ansible/{{ zuul_ansible_version }}/bin/ansible-playbook
        src/opendev.org/zuul/zuul/playbooks/zuul-stream/fixtures/test-stream-failure.yaml
      register: failed_results
      failed_when: "failed_results.rc != 2"
      environment:
        ANSIBLE_CALLBACK_PLUGINS: "{{ ara_callback_plugins.stdout }}:{{ python_path }}/zuul/ansible/base/callback"
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ZUUL_JOBDIR: "{{ ansible_user_dir}}"
        PYTHONPATH: "{{ python_path }}"

    - name: Validate output - setupvar
      shell: |
        egrep "^.*\| node1 \|\s+\"setupvar\": {" job-output.txt
        egrep "^.*\| node2 \|\s+\"setupvar\": {" job-output.txt

    - name: Validate output - shell task
      shell: |
        egrep "^.*\| node1 \| 1: lo:" job-output.txt
        egrep "^.*\| node2 \| 1: lo:" job-output.txt

    - name: Validate output - loop with items
      shell: |
        egrep "^.+\| node1 \| ok: Item: item1" job-output.txt
        egrep "^.+\| node1 \| ok: Item: item2" job-output.txt
        egrep "^.+\| node1 \| ok: Item: item3" job-output.txt
        egrep "^.+\| node2 \| ok: Item: item1" job-output.txt
        egrep "^.+\| node2 \| ok: Item: item2" job-output.txt
        egrep "^.+\| node2 \| ok: Item: item3" job-output.txt

    - name: Validate output - loop with complex items
      shell: |
        egrep "^.+\| node1 \| ok: Item: Runtime" job-output.txt
        egrep "^.+\| node2 \| ok: Item: Runtime" job-output.txt

    - name: Validate output - shell task with exception
      shell: |
        egrep "^.+\| node1 \| (OSError|FileNotFoundError).+\/shelltask\/" job-output.txt
        egrep "^.+\| node2 \| (OSError|FileNotFoundError).+\/shelltask\/" job-output.txt

    - name: Validate output - item loop with exception
      shell: |
        egrep "^.+\| node1 \| (OSError|FileNotFoundError).+\/itemloop\/" job-output.txt
        egrep "^.+\| node2 \| (OSError|FileNotFoundError).+\/itemloop\/" job-output.txt

    - name: Validate output - failure shell task with exception
      shell: |
        egrep "^.+\| node1 \| (OSError|FileNotFoundError).+\/failure-shelltask\/" job-output.txt
        egrep "^.+\| node2 \| (OSError|FileNotFoundError).+\/failure-shelltask\/" job-output.txt

    - name: Validate output - failure item loop with exception
      shell: |
        egrep "^.+\| node1 \| (OSError|FileNotFoundError).+\/failure-itemloop\/" job-output.txt
        egrep "^.+\| node2 \| (OSError|FileNotFoundError).+\/failure-itemloop\/" job-output.txt

    - name: Validate output - binary data
      shell: |
        egrep "^.*\| node1 \| \\\\x80abc" job-output.txt
        egrep "^.*\| node2 \| \\\\x80abc" job-output.txt
