- hosts: controller
  tasks:
    - name: Create script
      copy:
        dest: /tmp/test.sh
        content: |
          exec 3>&1
          exec 6> >( /home/zuul/src/git.openstack.org/openstack-dev/devstack/tools/outfilter.py -v >&3 )
          wget http://tarballs.openstack.org/etcd/v3.1.7/etcd-v3.1.7-linux-amd64.tar.gz -O /home/zuul/etcd-v3.1.7-linux-amd64.tar.gz
    - name: Run script
      shell: stdbuf -oL -eL bash -x /tmp/test.sh
      become: true
      args:
        executable: /bin/bash
