- hosts: controller
  tasks:

    - name: Run ansible
      command: ansible-playbook -vvv src/git.openstack.org/openstack-infra/zuul/playbooks/zuul-stream/fixtures/test-stream.yaml
      environment:
        ZUUL_JOB_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"
        ARA_LOG_CONFIG: "{{ ansible_user_dir}}/logging.json"

    - name: Validate output - setupvar
      command: fgrep '"setupvar": {' job-output.txt

    - name: Validate output - shell task
      command: fgrep 'link/loopback' job-output.txt

    - name: Validate output - loop with items
      command: fgrep 'Item: item1' job-output.txt

    - name: Generate ARA html
      command: ara generate html ara-output

    - name: Compress ARA html
      command: gzip --recursive --best ara-output
