- hosts: controller
  tasks:
    - name: Run wget
      shell: wget http://tarballs.openstack.org/etcd/v3.1.7/etcd-v3.1.7-linux-amd64.tar.gz -O /home/zuul/etcd-v3.1.7-linux-amd64.tar.gz
      args:
        executable: /bin/bash
