- hosts: controller
  tasks:

    - set_fact:
        output_dir: "{{ zuul.executor.log_root }}/stream-files"

    - name: Make log subdir
      file:
        path: "{{ output_dir }}"
        state: directory
      delegate_to: localhost

    - name: Show the files
      command: ls

    - name: Fetch files
      synchronize:
        src: "{{ ansible_user_dir }}/{{ item }}"
        dest: "{{ output_dir }}"
        mode: pull
      with_items:
        - logging.json
        - ansible.cfg
        - job-output.txt
        - job-output.json
        - ara-output
