- hosts: controller
  tasks:

    - name: Generate ARA html
      command: /usr/lib/zuul/ansible/{{ zuul_ansible_version }}/bin/ara-manage generate ara-report

#    - name: Compress ARA html
#      command: gzip --recursive --best ara-output

    - name: Fetch ARA files
      synchronize:
        src: "{{ ansible_user_dir }}/ara-report"
        dest: "{{ zuul.executor.log_root }}/stream-files"
        mode: pull
