- hosts: controller
  tasks:

    - set_fact:
        output_dir: "{{ zuul.executor.log_root }}/stream-files"

    - name: Make log subdir
      file:
        path: "{{ output_dir }}"
        state: directory
      delegate_to: localhost

    - name: Rename job-output.txt
      command: mv job-output.txt stream-job-output.txt

    - name: Generate ARA html
      command: ara generate html ara-output

    - name: Compress ARA html
      command: gzip --recursive --best ara-output

    - name: Fetch files
      synchronize:
        src: "{{ ansible_user_dir }}/{{ item }}"
        dest: "{{ output_dir }}"
        mode: pull
      with_items:
        - logging.json
        - ansible.cfg
        - stream-job-output.txt
        - job-output.json
        - ara-output
