- hosts: controller
  roles:

    - role: ensure-pip

    - role: bindep
      bindep_profile: test
      bindep_dir: src/opendev.org/zuul/zuul

  post_tasks:

    - name: Install docker
      include_role:
        name: ensure-docker

    - name: Setup 2.7 container environment
      include_tasks: container.yaml
      args:
        container_version: 'py27'
        container_tag: 'zuul_python27'
        container_ssh_port: '2022'
        container_console_port: '19887'
        container_ssh_port: '2022'
        container_loopback_address: '127.0.0.2'

    - name: Setup 3.11 container environment
      include_tasks: container.yaml
      args:
        container_version: 'py311'
        container_tag: 'zuul_python311'
        container_ssh_port: '2023'
        container_console_port: '19888'
        container_loopback_address: '127.0.0.3'

    - name: Setup inventory
      include_tasks: create-inventory.yaml

    - name: Install pip
      shell: |+
        python3 -m pip install --upgrade pip setuptools wheel
      become: yes

    - name: Build wheel
      shell:
        chdir: src/opendev.org/zuul/zuul
        cmd: |+
          python3 setup.py bdist_wheel

    - name: Install software
      shell: |+
        python3 -m pip install src/opendev.org/zuul/zuul/dist/*.whl
      become: yes

    - name: Install managed ansible versions
      command: /usr/local/bin/zuul-manage-ansible -v
      become: yes
      environment:
        # This appears to be necessary because without it the virtualenvs
        # that virtualenv creates are not actually virtualenvs. They are just
        # aliases for the root python installation instead. Then we try to
        # install multiple ansible versions to the root (via multiple fake
        # venvs) and the installation fails due to conflicts.
        SETUPTOOLS_USE_DISTUTILS: stdlib

    - name: Copy ansible.cfg
      template:
        src: templates/ansible.cfg.j2
        dest: "{{ ansible_user_dir }}/ansible.cfg"

    - name: Generate logging config
      command: python3 src/opendev.org/zuul/zuul/zuul/ansible/logconfig.py
