- hosts: controller
  roles:

    - role: bindep
      bindep_profile: test
      bindep_dir: src/git.openstack.org/openstack-infra/zuul
      bindep_command: /usr/bindep-env/bin/bindep

  post_tasks:

    - name: Install software
      command: pip install src/git.openstack.org/openstack-infra/zuul src/git.openstack.org/openstack/ara
      become: yes

    - name: Copy inventory
      copy:
        src: "{{ zuul.executor.log_root }}/zuul-info/inventory.yaml"
        dest: "{{ ansible_user_dir }}/inventory.yaml"

    - name: Copy ansible.cfg
      template:
        src: templates/ansible.cfg.j2
        dest: "{{ ansible_user_dir }}/ansible.cfg"
