---
- name: "Include task check-pipeline-ok"
  include_tasks: check-pipeline.yaml

- name: "Approve changes: {{projectname}}"
  uri:
    url: "http://localhost:8080/a/changes/{{ changeinfo.id }}/revisions/{{ changeinfo.current_revision }}/review"
    method: POST
    user: admin
    password: secret
    status_code: 200
    body_format: json
    body:
      labels:
        Code-Review: "+2"
        Workflow: "+1"

- name: "Include task gate-pipeline"
  include_tasks: gate-pipeline.yaml
