---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-zuul
    local: true
    run_playbooks:
      - gate-first-patch.yaml
  environment:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile={{ workspace }}/known_hosts"
  tasks:
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
