---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-zuul
    local: true
    zuul_tutorial_confignum: 1
    run_playbooks:
      - job-secrets.yaml
  tasks:
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
