---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-zuul
    local: true
    skip_quick_start: no
    run_playbooks:
      - job-secrets.yaml
  tasks:
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
