---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-zuul
    local: true
    run_playbooks:
      - gate-first-patch.yaml
  tasks:
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
