---
- hosts: localhost
  vars:
    workspace: /tmp/tutorial-zuul
    local: true
    skip_quick_start: no
    zuul_tutorial_confignum: 0
    run_playbooks:
      - gate-first-patch.yaml
      - use-zuul-jobs.yaml
      - gate-pipeline.yaml
      - job-secrets.yaml
      - job-dependencies.yaml
  environment:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile={{ workspace }}/known_hosts"
  tasks:
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
