---
- hosts: all
  vars:
    workspace: /tmp/tutorial-zuul
    local: false
  environment:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile={{ workspace }}/known_hosts"
  roles:
    - name: ensure-docker
      use_upstream_docker: false
    - use-buildset-registry
  tasks:
    - name: Install git-review
      command: python3 -m pip install git-review
      become: true
    - name: Install upstream docker-compose
      command: python3 -m pip install docker-compose
      become: true
    - name: Run tutorial
      include_tasks: run-tutorial.yaml
