- hosts: all
  tasks:

    - name: Collect zookeeper logs
      # shell: "journalctl -u zookeeper > {{ zuul_output_dir }}/logs/zookeeper.log"
      shell: "cp /var/log/zookeeper/zookeeper.log {{ zuul_output_dir }}/logs/zookeeper.log
      become: yes
