#!/bin/bash

# Modify standard Gerrit config before starting
git config -f /var/gerrit/etc/gerrit.config gerrit.canonicalWebUrl http://localhost:8080/
git config -f /var/gerrit/etc/gerrit.config gerrit.ui POLYGERRIT
git config -f /var/gerrit/etc/gerrit.config sendemail.enable false
git config -f /var/gerrit/etc/gerrit.config noteDb.changes.autoMigrate true

# Launch Gerrit
/var/gerrit/bin/gerrit.sh run
