- hosts: all
  roles:
    - ensure-dstat-graph
    - run-dstat
    - role: ensure-zookeeper
      zookeeper_use_tls: true
  tasks:
    - name: Add zuul user to systemd-journal group for journal access
      user:
        name: zuul
        append: true
        groups: systemd-journal
      become: yes
    - name: Reset the connection allowing the above group change to take effect
      meta: reset_connection
    - name: Make mysql error log readable
      file:
        path: /var/log/mysql
        state: directory
        mode: 'o+rx'
      become: yes
    # We touch the file rather than simply update perms on the file because
    # Jammy mariadb doesn't seem to create this file at all nor use it. But
    # Focal (python3.8 job) does. Writing the tasks this way makes it work
    # for both versions.
    - name: Make mysql error log readable
      file:
        path: /var/log/mysql/error.log
        state: touch
        mode: '0644'
      become: yes
