- name: Run zuul_stream
  zuul_stream:

- name: Create workspace directory.
  file:
    path: "{{ prepare_workspace_root }}"
    owner: zuul
    group: zuul
    state: directory

- name: Synchronize git repos to workspace directory.
  synchronize:
    dest: "{{ prepare_workspace_root }}"
    src: "{{ zuul.launcher.git_root }}"
