- name: Ensure console.log does not exist.
  file:
    path: /tmp/console.log
    state: absent

- name: Start zuul_console daemon.
  zuul_console:
    path: /tmp/console.log
    port: 19885
  tags:
    - skip_ansible_lint

- name: Display net-info.
  shell: |
    export PATH=$PATH:/sbin
    if [ -f /etc/dib-builddate.txt ]; then
        echo "Image build date"
        echo "================"
        cat /etc/dib-builddate.txt
    fi
    echo "Host & kernel"
    echo "============="
    uname -a
    echo "Network interface addresses..."
    echo "=============================="
    ip address show
    echo "Network routing tables..."
    echo "========================="
    ip route show
    ip -6 route show
    echo "Network neighbors..."
    echo "===================="
    ip neighbor show
    echo "Route to Git mirror..."
    echo "======================"
    traceroute6 -n git.openstack.org \
        || traceroute -n git.openstack.org \
        || true

- name: Create workspace directory.
  file:
    path: "{{ zuul_workspace_root }}"
    owner: zuul
    group: zuul
    state: directory

- name: Synchronize src repos to workspace directory.
  synchronize:
    dest: "{{ zuul_workspace_root }}"
    src: "{{ zuul.executor.src_root }}"
