- hosts: all
  tasks:
    - synchronize:
        src: test.sh
        dest: "{{ ansible_user_dir }}"
    - synchronize:
        src: test2.sh
        dest: "{{ ansible_user_dir }}"
    - synchronize:
        src: functions
        dest: "{{ ansible_user_dir }}"
    - shell:
        cmd: |
          set -x

          ps -x
          pwd
          echo "start"
          ~/test.sh
          echo "end"
        executable: /bin/bash
