- kind: Secret
  apiVersion: v1
  metadata:
    name: os-client-config-secure
  stringData:
    secure.yaml: |+
      clouds:
        nodepool-cloud1:
          auth:
            username: 'user'
            password: 'example'
