---
- name: Store dummy Pypi test Info
  set_fact:
    dummy_pypi_username: adummyaccount
    dummy_pypi_password: adummypassword
    dummy_pypi_projectname: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: Copy config-project in zuul-config
  copy:
    src: ../../doc/source/examples/test1-job-secrets/config-project/
    dest: "{{ workspace }}/zuul-config/"

- name: Copy tools encrypt_secret.py in workspace
  copy:
    src: ../../tools/encrypt_secret.py
    dest: "{{ workspace }}/"
    mode: '0755'

- name: Generate secret
  shell:
    chdir: "{{ workspace }}/zuul-config/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      echo "config-secret" > ../config-project-password.txt
      ../encrypt_secret.py --tenant example-tenant --infile ../config-project-password.txt --outfile zuul.d/my-secret.yaml http://localhost:9000/ zuul-config
      sed -i -e "s/<name>/my-publication-secret/; s/<fieldname>/password/; s/^\( *\)password:/\1hostname: publication-host.example.com\n\1password:/" zuul.d/my-secret.yaml

- name: Commit and upload zuul-config
  shell:
    chdir: "{{ workspace }}/zuul-config/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git add -A .
      git commit -m "Provide my publication job"
      git review

- name: Check Zuul check status zuul-config is ok
  include_tasks: ../setup-tutorial/check-pipeline.yaml
  vars:
    item: zuul-config

- name: Approve changes
  uri:
    url: "http://localhost:8080/a/changes/{{ changeinfo.id }}/revisions/{{ changeinfo.current_revision }}/review"
    method: POST
    user: admin
    password: secret
    status_code: 200
    body_format: json
    body:
      labels:
        Code-Review: "+2"
        Workflow: "+1"

- name: Check Zuul gate status zuul-config is ok
  include_tasks: ../setup-tutorial/change-merged.yaml
  vars:
    item: zuul-config
    check_timeout: 180
    gate_timeout: 180

- name: Init Test1
  include_tasks: ../setup-tutorial/init-repository.yaml
  vars:
    item: test1

- name: Setup repository test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git review -s

- name: Copy zuul.yaml in test1
  copy:
    src: ../../doc/source/examples/test1-job-secrets/config-project-test1/zuul.yaml
    dest: "{{ workspace }}/test1/.zuul.yaml"

- name: Commit and upload hello.py in test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git add .zuul.yaml
      git commit -m "Configure project pipelines"
      git review

- name: Check Zuul check status test1 is ok
  include_tasks: ../setup-tutorial/check-pipeline.yaml
  vars:
    item: test1
    check_timeout: 90

- name: Init Test1
  include_tasks: ../setup-tutorial/init-repository.yaml
  vars:
    item: test1

- name: Setup repository test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git review -s

- name: Copy hoz-4-demo-repo.tgz in workspace
  copy:
    src: ../../doc/source/examples/test1-gate-pipeline/hoz-4-demo-repo.tgz
    dest: "{{ workspace }}/"
- name: Copy tox.ini in test1
  copy:
    src: ../../doc/source/examples/test1-gate-pipeline/tox.ini
    dest: "{{ workspace }}/test1/tox.ini"
- name: Copy setup.py in test1
  copy:
    src: ../../doc/source/examples/test1-job-secrets/untrusted-project/setup.py
    dest: "{{ workspace }}/test1/"
- name: Copy playbooks in test1
  copy:
    src: ../../doc/source/examples/test1-job-secrets/untrusted-project/playbooks/
    dest: "{{ workspace }}/test1/playbooks/"
- name: Copy append_zuul.yaml in workspace
  copy:
    src: ../../doc/source/examples/test1-job-secrets/untrusted-project/append_zuul.yaml
    dest: "{{ workspace }}/"

- name: Generate secret
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      echo "{{dummy_pypi_password}}" > ../test1-project-password.txt
      ../encrypt_secret.py --tenant example-tenant --infile ../test1-project-password.txt --outfile .zuul.yaml http://localhost:9000/ test1
      sed -i -e "s/<name>/my-pypi-secret/; s/<fieldname>/password/; s/^\( *\)password:/\1username: {{dummy_pypi_username}}\n\1password:/" .zuul.yaml
      cat ../append_zuul.yaml >> .zuul.yaml
      sed -i -e "s/changethistoauniqname/{{dummy_pypi_projectname}}/" setup.py

- name: Commit and upload in test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git add -A
      git commit -m "Provide my upload-pypi job"
      git review

- name: Check Zuul check status test1 is ok
  include_tasks: ../setup-tutorial/check-pipeline.yaml
  vars:
    item: test1
    check_timeout: 180

- name: Approve changes
  uri:
    url: "http://localhost:8080/a/changes/{{ changeinfo.id }}/revisions/{{ changeinfo.current_revision }}/review"
    method: POST
    user: admin
    password: secret
    status_code: 200
    body_format: json
    body:
      labels:
        Code-Review: "+2"
        Workflow: "+1"

- name: Check Zuul gate status test1 is ok
  include_tasks: ../setup-tutorial/change-merged.yaml
  vars:
    item: test1
    check_timeout: 180
    gate_timeout: 180


- name: Copy append_config_pipeline.yaml in workspace
  copy:
    src: ../../doc/source/examples/test1-job-secrets/untrusted-project/append_config_pipeline.yaml
    dest: "{{ workspace }}/"

- name: Add release pipeline to zuul-config pipelines
  shell:
    chdir: "{{ workspace }}/zuul-config/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      cat ../append_config_pipeline.yaml >> zuul.d/pipelines.yaml

- name: Commit and upload zuul-config
  shell:
    chdir: "{{ workspace }}/zuul-config/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git add -A .
      git commit -m "Add release pipeline"
      git review

- name: Check Zuul check status zuul-config is ok
  include_tasks: ../setup-tutorial/check-pipeline.yaml
  vars:
    item: zuul-config
    check_timeout: 180

- name: Approve changes
  uri:
    url: "http://localhost:8080/a/changes/{{ changeinfo.id }}/revisions/{{ changeinfo.current_revision }}/review"
    method: POST
    user: admin
    password: secret
    status_code: 200
    body_format: json
    body:
      labels:
        Code-Review: "+2"
        Workflow: "+1"

- name: Check Zuul gate status zuul-config is ok
  include_tasks: ../setup-tutorial/change-merged.yaml
  vars:
    item: zuul-config
    check_timeout: 180
    gate_timeout: 180

- name: "Wait for release pipeline to come up"
  uri:
    url: "http://localhost:9000/api/tenant/example-tenant/status"
    method: GET
    return_content: true
  register: result
  until: result.status == 200 and (result.content|from_json).pipelines|length >= 3
  delay: 1
  retries: 30
- debug:
    msg: "number of retries: {{ result.attempts }}"

- name: Push tag test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      git tag -a -m 0.0.1 0.0.1
      git push gerrit 0.0.1

- name: "Get project Info on Pipy test"
  uri:
    url: "https://test.pypi.org/pypi/{{dummy_pypi_projectname}}/json"
    method: GET
    status_code: 200
    return_content: true
  register: result
  until: result.status == 200
  delay: 15
  retries: 6
  ignore_errors: true

- debug:
    msg: "print project name from pypi: {{ (result.content|from_json).info.name }}"
  when: result.status == 200
