- hosts: node
  name: Job body
  tasks:
  - name: shell task expanded from JJB
    command: |
      echo JJB template: gate-{name}-pep8-{node}
    args:
      chdir: /home/jenkins/workspace/gate-os-client-config-pep8-ubuntu-xenial
    environment: '{{ zuul.environment }}'
  - copy:
      dest: /tmp/00c4604ef2c04adc9f557384d2577021.sh
      mode: 365
      src: /tmp/tmpeb6j1Q/ansible/scripts/00c4604ef2c04adc9f557384d2577021.sh
  - name: shell task expanded from JJB
    shell: |
      CLONEMAP=`mktemp`
      REQS_DIR=`mktemp -d`
      function cleanup {
          mkdir -p $WORKSPACE
          rm -rf $CLONEMAP $REQS_DIR
      }
      trap cleanup EXIT
      cat > $CLONEMAP << EOF
      clonemap:
        - name: $ZUUL_PROJECT
          dest: .
      EOF
      # zuul cloner works poorly if there are 2 names that are the
      # same in here.
      if [[ "$ZUUL_PROJECT" != "openstack/requirements" ]]; then
      cat >> $CLONEMAP << EOF
        - name: openstack/requirements
          dest: $REQS_DIR
      EOF
      fi
      /usr/zuul-env/bin/zuul-cloner -m $CLONEMAP --cache-dir /opt/git \
          git://git.openstack.org $ZUUL_PROJECT openstack/requirements
      # REQS_DIR is not set for openstack/requirements and there's also
      # no need to copy in this case.
      if [[ "$ZUUL_PROJECT" != "openstack/requirements" ]]; then
          cp $REQS_DIR/upper-constraints.txt ./
      fi
    args:
      chdir: /home/jenkins/workspace/gate-os-client-config-pep8-ubuntu-xenial
    environment: '{{ zuul.environment }}'
  - name: shell task expanded from JJB
    shell: /usr/local/jenkins/slave_scripts/install-distro-packages.sh
    args:
      chdir: /home/jenkins/workspace/gate-os-client-config-pep8-ubuntu-xenial
    environment: '{{ zuul.environment }}'
  - name: shell task expanded from JJB
    shell: |
      sudo rm -f /etc/sudoers.d/jenkins-sudo
      # Prove that general sudo access is actually revoked
      ! sudo -n true
    args:
      chdir: /home/jenkins/workspace/gate-os-client-config-pep8-ubuntu-xenial
    environment: '{{ zuul.environment }}'
  - name: shell task expanded from JJB
    shell: /usr/local/jenkins/slave_scripts/run-pep8.sh pep8
    args:
      chdir: /home/jenkins/workspace/gate-os-client-config-pep8-ubuntu-xenial
    environment: '{{ zuul.environment }}'
