version: '2'
services:
  gerrit:
    build:
      dockerfile: gerrit-Dockerfile
      context: ./
    ports:
      - "8080:8080"
      - "29418:29418"
  gerritconfig:
    build:
      dockerfile: ansible-Dockerfile
      context: ./
    depends_on:
      - gerrit
    volumes:
      - "sshkey:/var/ssh"
      - "nodessh:/var/node"
      - "./playbooks/:/var/playbooks/"
    command: "ansible-playbook /var/playbooks/setup.yaml"
  zk:
     image: zookeeper
  scheduler:
    depends_on:
      - gerritconfig
      - zk
    command: "sh -c 'ansible-playbook /var/playbooks/scheduler.yaml; zuul-scheduler -d'"
    image: zuul/zuul
    volumes:
      - "./etc_zuul/:/etc/zuul/"
      - "./playbooks/:/var/playbooks/"
      - "sshkey:/var/ssh"
      - /var/lib/zuul
  web:
    command: "zuul-web -d"
    depends_on:
      - scheduler
    ports:
      - "9000:9000"
    image: zuul/zuul
    volumes:
      - "./etc_zuul/:/etc/zuul/"
  executor:
    privileged: true
    command: "sh -c 'ansible-playbook /var/playbooks/executor.yaml; zuul-executor -d'"
    depends_on:
      - scheduler
    image: zuul/zuul
    volumes:
      - "./etc_zuul/:/etc/zuul/"
      - "./playbooks/:/var/playbooks/"
      - "sshkey:/var/ssh"
      - "logs:/var/logs"
  node:
    build:
      dockerfile: node-Dockerfile
      context: ./
    volumes:
      - "nodessh:/root/.ssh"
  launcher:
    command: "nodepool-launcher -d"
    depends_on:
      - zk
    image: zuul/nodepool
    volumes:
      - "./etc_nodepool/:/etc/nodepool/"
    ports:
      - "8022:8022"
  logs:
    image: httpd:alpine
    ports:
      - "8000:80"
    volumes:
      - "logs:/usr/local/apache2/htdocs"

volumes:
  sshkey:
  nodessh:
  logs:
