- secret:
    name: zuul_docker_login
    data:
      user: !encrypted/pkcs1-oaep
        - pSaUNwfFZRjH+hG56BmkxMB+inutl26GOBpLNbyHf8gv50MOJ/0Pc8PvhVoYES+bWHlhy
          I/T5S5nPVkPZGmTe39MggLjp/gd5bk1paYl45JsOOjy2R9mCWSu7kG+SoQ5NzUmqPUChX
          8pMmoq2hNxf89pDZINz1yrgeOh3QuLjzZV0jiV5IsJ5E1O1gw4sJdyGnHmWMKmBiCS6Dr
          I6jOkRNDnyb9S4e00qAyultl9ESAy+7EA1BWt18+qlPlHBlfbWDoOL+8s+nYNHl3IzLbj
          /gz2/wzzaD6hCV8yBpEx7AYS/eie29KKV5R5JcvBbno1B8uezb9swj5UMJ7VqyARfjXYH
          Y3KKAqYN51xQPF3pXmSD0baUi8uwOyqwYsaryQnwrkC5izuDtvsxVv2HvTqvhPXje074O
          kmRmQB3UbK4nXKXwsdlRT/PwNb2i09i9DbERHZPhP2X0gN6nS/UVDce+Wwegr70LhTDJM
          e/7OAE0gfoioxTTug0FF0+2wsGmJM/ZNhNqDKgqg8m+GPfW5EjTWS3HawpLRN3eRQfPxH
          0JPXfvbmLlA7TPc4PeBM5m1BfvSTdl5O3ecuG/f+e/oq1wxeiAzNW5IToNC2vXKu/27Nk
          RyLiL5/jjadveRjHEYdJdBgxJlibblJbEzguY1T0CKpp3wlPrw3YtqlD+tXT98=

      password: !encrypted/pkcs1-oaep
        - RylN0EXN4zTjQ9zmyVlTt6T0Nzknybt0+EswX4eKz+2qGznAJYpuYua5cal4R8xOwHPUv
          VcLqMsNvoQ9WdUhxuWep5IVT/gz/FNReREudvr+othGh1qI2tK88lyyaxdOHi3Yu7ovC2
          tSHLpw46tWpoRYqSQA3XsX9mgqL54VeHulvl/a28anO94uL5xeL0fGmkl6T5dd2de8xWx
          ewyoH4Nt6M0kYcpwZS1pz9C5phRH7Ph8uVdfan6NMXHSonFaRlXbVlC2GwzHsesuXFdNi
          V7QeSo8ZKF728AA5ySTp+E3ze1YDG6on+ljcdHZ7qZQpYmiULNBQKlkdmjcQS7PTuFxoV
          RFwB92N93Flb0f6E7hxT56Sdpd51Wt71vrUJ2mwY73y78M5fY+Tqgk82JkoNPZucgi+mk
          vqUNQbW+IB7SIvq8xfMnsx8LnfDc8yEEGXi5hpP6MH5wd3qSo/FL1d6YbIDIN1yaQpEip
          aW3I7TTAYJrW5IdvywDEfuSYgqUxdXeRA4TRD9yx3bq3chOSDNQ5nvCMKnlgL/wORCZ+W
          4493yfAjjJNxXkPsxQZsk0SZmHoWKj5nzMkJBDsoqEaXgHQO1CojHgtt2FZ9wjIu7+W5D
          O/Ww6Fw8Tiuj6xS8oLPRQeAWZ9RpbnSj/k+nN+Du+h6stt9WS/X3Kp0h+k7gnw=
