---
- name: Init Test1
  include_tasks: ../setup-tutorial/init-repository.yaml
  vars:
    item: test1
- name: Make test change in test1
  copy:
    src: ../../doc/source/examples/test1/
    dest: "{{ workspace }}/test1/"
- name: Commit and upload test change in test1
  shell:
    chdir: "{{ workspace }}/test1/"
    executable: /bin/bash
    cmd: |
      {{ ssh_agent.stdout }}
      mv zuul.yaml .zuul.yaml
      git add .zuul.yaml playbooks
      git commit -m "Add test Zuul job"
      git review
- name: Query open changes
  uri:
    url: http://localhost:8080/a/changes/?q=status:open+project:test1&o=CURRENT_REVISION
    method: GET
    user: admin
    password: secret
    return_content: true
  register: changes
- name: Wait for Zuul to report
  uri:
    url: "http://localhost:8080/a/changes/{{ (changes.content[5:]|from_json)[0].id }}/detail"
    method: GET
    user: admin
    password: secret
    return_content: true
  register: result
  until: result.status == 200 and (result.content[5:]|from_json).messages|length > 1
  delay: 10
  retries: 120
- debug:
    msg: "number of retries: {{ result.attempts }}"
- name: Find the log URL
  set_fact:
    log_url: "{{ (result.content[5:]|from_json).messages[1].message|regex_search('(http://[^ ]*)') }}"
- debug:
    msg: "{{ log_url }}"
- name: Fetch log URL
  get_url:
    url: "{{ log_url }}job-output.txt"
    dest: "{{ workspace }}/job-output.txt"
- name: Verify log contents
  command: "grep 'Hello world!' {{ workspace }}/job-output.txt"
