- hosts: localhost
  vars:
    workspace: /tmp/tutorial-gate-first-patch-test
    local: true
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ssh_agent:
      stdout: ''
  tasks:
    - include_tasks: ../setup-tutorial/setup.yaml
    - include_tasks: main.yaml
    - name: Create logs directory
      file:
        state: directory
        path: "{{ ansible_user_dir }}/logs"
        mode: 0755
    - name: Save docker log files
      shell: |
        docker logs examples_gerrit_1 > {{ ansible_user_dir }}/logs/gerrit.log 2>&1
        docker logs examples_gerritconfig_1 > {{ ansible_user_dir }}/logs/gerritconfig.log 2>&1
        docker logs examples_zk_1 > {{ ansible_user_dir }}/logs/zk.log 2>&1
        docker logs examples_mysql_1 > {{ ansible_user_dir }}/logs/mysql.log 2>&1
        docker logs examples_scheduler_1 > {{ ansible_user_dir }}/logs/scheduler.log 2>&1
        docker logs examples_web_1 > {{ ansible_user_dir }}/logs/web.log 2>&1
        docker logs examples_executor_1 > {{ ansible_user_dir }}/logs/executor.log 2>&1
        docker logs examples_node1_1 > {{ ansible_user_dir }}/logs/node.log 2>&1
        docker logs examples_launcher_1 > {{ ansible_user_dir }}/logs/launcher.log 2>&1
        docker logs examples_logs_1 > {{ ansible_user_dir }}/logs/logs.log 2>&1
