- hosts: controller
  tasks:
#    - name: pause
#      pause:
#        minutes: 5
    - name: run-tox
      shell: /usr/local/bin/slave_scripts/run-tox.sh pep8
      args:
        chdir: /home/zuul/workspace/git/openstack-infra/zuul/
