- hosts: all
  tasks:
    - name: Collect tox logs.
      synchronize:
        dest: "{{ zuul.launcher.log_root }}/tox/"
        mode: pull
        src: "/home/zuul/workspace/src/{{ zuul.project }}/.tox/pep8/log/"

