- hosts: all
  tasks:
    - name: Collect console log.
      synchronize:
        dest: "{{ zuul.launcher.log_root }}/{{ zuul.uuid }}/"
        mode: pull
        src: "/tmp/console.log"

    - name: Collect tox logs.
      synchronize:
        dest: "{{ zuul.launcher.log_root }}/{{ zuul.uuid }}/tox"
        mode: pull
        src: "/home/zuul/workspace/src/{{ zuul.project }}/.tox/pep8/log/"

    - name: publish tox logs.
      copy:
        src: "{{ zuul.launcher.log_root }}/"
        dest: "/opt/zuul-logs/"
      delegate_to: 127.0.0.1
