- hosts: all
  tasks:
    - name: Install yarn modules
      args:
        chdir: "{{ zuul.project.src_dir }}"
      command: yarn install

    - name: Build web files
      args:
        chdir: "{{ zuul.project.src_dir }}"
      command: npm run build:dist
