- hosts: all
  vars:
    zuul_work_dir: "src/{{ zuul.project.canonical_name }}"
  tasks:
    - name: Install migration dependencies
      command: "pip3 install --user {{ zuul_work_dir }}[migrate]"
    - name: Migrate the data
      command: "zuul-migrate zuul/layout.yaml jenkins/jobs nodepool/nodepool.yaml . --mapping=zuul/mapping.yaml -v"
      args:
        chdir: src/git.openstack.org/openstack-infra/project-config
    - name: Collect generated files
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "{{ zuul_work_dir }}/zuul.d"
        verify_host: true
      no_log: true
