- hosts: all
  tasks:
    - name: Install migration dependencies
      command: "pip3 install --user src/git.openstack.org/openstack-infra/zuul[migrate]"
    - name: Migrate the data
      command: "zuul-migrate zuul/layout.yaml jenkins/jobs nodepool/nodepool.yaml . --mapping=zuul/mapping.yaml -v"
      args:
        chdir: src/git.openstack.org/openstack-infra/project-config
    - name: Collect generated files
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "src/git.openstack.org/openstack-infra/project-config/zuul.d"
        verify_host: true
      no_log: true
