- hosts: all
  tasks:

    - name: Install migration dependencies
      command: "python3 -m pip install --user src/git.openstack.org/openstack-infra/zuul[migrate]"

    - name: Migrate the data
      command: "python3 ../zuul/zuul/cmd/migrate.py zuul/layout.yaml jenkins/jobs nodepool/nodepool.yaml . --mapping=zuul/mapping.yaml -v -m"
      args:
        chdir: src/git.openstack.org/openstack-infra/project-config

    - name: Collect generated files
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "src/git.openstack.org/openstack-infra/project-config/zuul.d"
        verify_host: true
      no_log: true
